import { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: '1',
    name: 'Vaso Verde Cônico',
    slug: 'vaso-verde-conico',
    description: 'Ideal para suculentas e ambientes internos.',
    price: 59.9,
    images: ['/images/vaso1-1.png', '/images/vaso1-2.png'],
    rating: 4.7,
    reviewCount: 143,
    isFull: true,
    isFreeShipping: true,
  },
  {
    id: '2',
    name: 'Vaso Branco Minimalista',
    slug: 'vaso-branco-minimalista',
    description: 'Design clean e sofisticado.',
    price: 89.9,
    images: ['/images/vaso2-2.png', '/images/vaso2-1.png'],
    rating: 4.3,
    reviewCount: 98,
    isFull: false,
    isFreeShipping: true,
  },
  {
    id: '3',
    name: 'Vaso Terracota Clássico',
    slug: 'vaso-terracota-classico',
    description: 'Estilo rústico ideal para jardins e varandas.',
    price: 39.9,
    images: ['/images/vaso3-2.png', '/images/vaso3-1.png'],
    rating: 2.4,
    reviewCount: 37,
    isFull: true,
    isFreeShipping: false,
  },
  {
    id: '4',
    name: 'Vaso Verde Cônico',
    slug: 'vaso-verde-conico',
    description: 'Ideal para suculentas e ambientes internos.',
    price: 59.9,
    images: ['/images/vaso1-1.png', '/images/vaso1-2.png'],
    rating: 4.7,
    reviewCount: 143,
    isFull: true,
    isFreeShipping: true,
  },
  {
    id: '5',
    name: 'Vaso Branco Minimalista',
    slug: 'vaso-branco-minimalista',
    description: 'Design clean e sofisticado.',
    price: 89.9,
    images: ['/images/vaso2-2.png', '/images/vaso2-1.png'],
    rating: 4.3,
    reviewCount: 98,
    isFull: false,
    isFreeShipping: true,
  },
  {
    id: '6',
    name: 'Vaso Terracota Clássico',
    slug: 'vaso-terracota-classico',
    description: 'Estilo rústico ideal para jardins e varandas.',
    price: 39.9,
    images: ['/images/vaso3-2.png', '/images/vaso3-1.png'],
    rating: 2.4,
    reviewCount: 37,
    isFull: true,
    isFreeShipping: false,
  },
];
